/**
 * Instrument voices, synthesised at runtime.
 *
 * Every sound in THE LAST MEMORY is generated by these three primitives:
 *   Drone  — the machine's own hum, always present, never resolving.
 *   Piano  — a struck string modelled with FM; the human element.
 *   Noise  — the archive tearing itself apart.
 */

export const midiToFreq = (m: number) => 440 * Math.pow(2, (m - 69) / 12);

/* ------------------------------------------------------------------ *
 * Drone — three detuned partials through a slowly breathing filter.
 * ------------------------------------------------------------------ */
export class DroneVoice {
  readonly output: GainNode;
  private readonly oscillators: OscillatorNode[] = [];
  private readonly filter: BiquadFilterNode;
  private readonly lfo: OscillatorNode;
  private readonly lfoGain: GainNode;
  private baseFreq = 55;

  constructor(private ctx: AudioContext) {
    this.output = ctx.createGain();
    this.output.gain.value = 0;

    this.filter = ctx.createBiquadFilter();
    this.filter.type = 'lowpass';
    this.filter.frequency.value = 320;
    this.filter.Q.value = 1.6;
    this.filter.connect(this.output);

    // Fundamental, a fifth, and a shimmering two-octave partial.
    const partials: Array<[number, OscillatorType, number]> = [
      [1, 'sine', 0.55],
      [1.5, 'triangle', 0.18],
      [4.01, 'sine', 0.06],
      [0.5, 'sine', 0.3],
    ];
    for (const [ratio, type, gain] of partials) {
      const osc = ctx.createOscillator();
      osc.type = type;
      osc.frequency.value = this.baseFreq * ratio;
      // Tiny detune keeps it alive rather than sterile.
      osc.detune.value = (Math.random() - 0.5) * 9;
      const g = ctx.createGain();
      g.gain.value = gain;
      osc.connect(g).connect(this.filter);
      osc.start();
      this.oscillators.push(osc);
      (osc as OscillatorNode & { _ratio?: number; _gain?: GainNode })._ratio = ratio;
    }

    // Filter breathing — a machine drawing breath it does not need.
    this.lfo = ctx.createOscillator();
    this.lfo.frequency.value = 0.045;
    this.lfoGain = ctx.createGain();
    this.lfoGain.gain.value = 140;
    this.lfo.connect(this.lfoGain).connect(this.filter.frequency);
    this.lfo.start();
  }

  setFrequency(freq: number, glideSeconds = 3) {
    if (Math.abs(freq - this.baseFreq) < 0.01) return;
    this.baseFreq = freq;
    const now = this.ctx.currentTime;
    for (const osc of this.oscillators) {
      const ratio = (osc as OscillatorNode & { _ratio?: number })._ratio ?? 1;
      osc.frequency.cancelScheduledValues(now);
      osc.frequency.setTargetAtTime(freq * ratio, now, glideSeconds / 3);
    }
  }

  setGain(value: number, seconds = 1.5) {
    const now = this.ctx.currentTime;
    this.output.gain.cancelScheduledValues(now);
    this.output.gain.setTargetAtTime(value, now, Math.max(0.02, seconds / 3));
  }

  /** Opens the filter as the world grows brighter/warmer. */
  setBrightness(value01: number, seconds = 2) {
    const now = this.ctx.currentTime;
    this.filter.frequency.setTargetAtTime(180 + value01 * 1800, now, seconds / 3);
  }

  /** Detune the whole stack — used when the archive destabilises. */
  setInstability(value01: number) {
    const now = this.ctx.currentTime;
    for (const osc of this.oscillators) {
      osc.detune.setTargetAtTime((Math.random() - 0.5) * 9 - value01 * 65, now, 0.4);
    }
    this.lfo.frequency.setTargetAtTime(0.045 + value01 * 1.9, now, 0.5);
  }

  dispose() {
    this.oscillators.forEach((o) => o.stop());
    this.lfo.stop();
  }
}

/* ------------------------------------------------------------------ *
 * Piano — 2-operator FM with a struck envelope and sympathetic decay.
 * ------------------------------------------------------------------ */
export interface PluckOptions {
  freq: number;
  velocity?: number;
  duration?: number;
  brightness?: number;
  detuneCents?: number;
}

export class PianoVoice {
  readonly output: GainNode;

  constructor(private ctx: AudioContext) {
    this.output = ctx.createGain();
    this.output.gain.value = 0;
  }

  setGain(value: number, seconds = 2) {
    const now = this.ctx.currentTime;
    this.output.gain.cancelScheduledValues(now);
    this.output.gain.setTargetAtTime(value, now, Math.max(0.02, seconds / 3));
  }

  play(at: number, opts: PluckOptions) {
    const { ctx } = this;
    const {
      freq,
      velocity = 0.6,
      duration = 4.2,
      brightness = 1.4,
      detuneCents = 0,
    } = opts;

    const carrier = ctx.createOscillator();
    carrier.type = 'sine';
    carrier.frequency.value = freq;
    carrier.detune.value = detuneCents;

    // Modulator at a non-integer ratio gives the inharmonic "wood and wire"
    // colour a pure sine can never have.
    const mod = ctx.createOscillator();
    mod.type = 'sine';
    mod.frequency.value = freq * 2.004;

    const modGain = ctx.createGain();
    modGain.gain.setValueAtTime(freq * brightness * velocity, at);
    modGain.gain.exponentialRampToValueAtTime(freq * 0.02, at + duration * 0.32);
    mod.connect(modGain).connect(carrier.frequency);

    const amp = ctx.createGain();
    amp.gain.setValueAtTime(0.0001, at);
    amp.gain.exponentialRampToValueAtTime(Math.max(0.0002, velocity), at + 0.006);
    amp.gain.exponentialRampToValueAtTime(velocity * 0.28, at + 0.42);
    amp.gain.exponentialRampToValueAtTime(0.0001, at + duration);

    // Gentle body resonance.
    const body = ctx.createBiquadFilter();
    body.type = 'peaking';
    body.frequency.value = freq * 1.98;
    body.Q.value = 2.4;
    body.gain.value = 4;

    carrier.connect(amp).connect(body).connect(this.output);

    carrier.start(at);
    mod.start(at);
    carrier.stop(at + duration + 0.15);
    mod.stop(at + duration + 0.15);
  }
}

/* ------------------------------------------------------------------ *
 * Noise — the sound of data failing.
 * ------------------------------------------------------------------ */
export class NoiseVoice {
  readonly output: GainNode;
  private readonly source: AudioBufferSourceNode;
  private readonly filter: BiquadFilterNode;

  constructor(private ctx: AudioContext) {
    this.output = ctx.createGain();
    this.output.gain.value = 0;

    this.filter = ctx.createBiquadFilter();
    this.filter.type = 'bandpass';
    this.filter.frequency.value = 900;
    this.filter.Q.value = 0.7;
    this.filter.connect(this.output);

    this.source = ctx.createBufferSource();
    this.source.buffer = createPinkNoise(ctx, 4);
    this.source.loop = true;
    this.source.connect(this.filter);
    this.source.start();
  }

  setGain(value: number, seconds = 1) {
    const now = this.ctx.currentTime;
    this.output.gain.cancelScheduledValues(now);
    this.output.gain.setTargetAtTime(value, now, Math.max(0.02, seconds / 3));
  }

  setCharacter(value01: number) {
    const now = this.ctx.currentTime;
    this.filter.frequency.setTargetAtTime(500 + value01 * 4200, now, 0.25);
    this.filter.Q.setTargetAtTime(0.7 + value01 * 5, now, 0.25);
  }

  /** A single tearing artefact — one packet of memory failing to decode. */
  burst(at: number, intensity: number) {
    const { ctx } = this;
    const src = ctx.createBufferSource();
    src.buffer = this.source.buffer;
    src.loop = true;
    src.playbackRate.value = 0.4 + Math.random() * 2.6;

    const bp = ctx.createBiquadFilter();
    bp.type = 'bandpass';
    bp.frequency.value = 300 + Math.random() * 5200;
    bp.Q.value = 3 + Math.random() * 14;

    const g = ctx.createGain();
    const dur = 0.03 + Math.random() * 0.22 * intensity;
    g.gain.setValueAtTime(0.0001, at);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002, 0.22 * intensity), at + 0.004);
    g.gain.exponentialRampToValueAtTime(0.0001, at + dur);

    src.connect(bp).connect(g).connect(this.output);
    src.start(at);
    src.stop(at + dur + 0.05);
  }

  dispose() {
    this.source.stop();
  }
}

/** Pink-ish noise (Voss-McCartney approximation) — warmer than white. */
export function createPinkNoise(ctx: BaseAudioContext, seconds: number): AudioBuffer {
  const rate = ctx.sampleRate;
  const length = Math.floor(rate * seconds);
  const buffer = ctx.createBuffer(2, length, rate);
  for (let ch = 0; ch < 2; ch++) {
    const data = buffer.getChannelData(ch);
    let b0 = 0,
      b1 = 0,
      b2 = 0,
      b3 = 0,
      b4 = 0,
      b5 = 0,
      b6 = 0;
    for (let i = 0; i < length; i++) {
      const white = Math.random() * 2 - 1;
      b0 = 0.99886 * b0 + white * 0.0555179;
      b1 = 0.99332 * b1 + white * 0.0750759;
      b2 = 0.969 * b2 + white * 0.153852;
      b3 = 0.8665 * b3 + white * 0.3104856;
      b4 = 0.55 * b4 + white * 0.5329522;
      b5 = -0.7616 * b5 - white * 0.016898;
      data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11;
      b6 = white * 0.115926;
    }
  }
  return buffer;
}
